name: Cron Job

on:
  # 设置每天的UTC时间 9点自动运行
  schedule:
    - cron: "0 9 * * *"

jobs:
  run:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
